- paged:
    queryParameters:
      start:
        description: The first page of results to return
        type: number
        example: 1
      pages:
        description: The number of pages of results to return
        type: number
        example: 3