pipeline {

    agent {
        label 'windows10'
    }

    stages {
        stage('Update AMF'){
            steps {
                // powershell returnStatus: true, script: 'amf-update/automate.ps1 source/AMF.Parser/'
                bat "dotnet amf-update/AmfUpdate.dll source/RAML.Parser/RAML.Parser.csproj false"
            }
        }
        stage('Build') {
            steps {
           		bat 'nuget restore source/RAML.Parser.sln'
        		bat "msbuild source/RAML.Parser.sln /p:Configuration=Release /p:Platform=\"Any CPU\""
            }
        }
        stage('Test') {
            steps {
                dir("source/RAML.Parser.TestRunner/bin/Release/"){
                    bat 'ConsoleApp2.exe'
                }
            }
        }
        stage('Pack') {
            steps {
                // zip files
                zip dir:'source/RAML.Parser/', zipFile: 'RAML.Parser.zip'
            }
        }        
    }

    post {
        always {
            archiveArtifacts '*.zip'
        }
        cleanup {
            
            cleanWs()
        }
    }
}