pipeline {

    agent {
        label 'windows10'
    }

    stages {
        stage('Update AMF'){
            steps {
                // powershell returnStatus: true, script: 'amf-update/automate.ps1 source/AMF.Parser/'
                bat "dotnet amf-update/AmfUpdate.dll source/AMF.Parser/AMF.Parser.csproj false"
            }
        }
        stage('Build') {
            steps {
           		bat 'nuget restore source/AMF.Parser.sln'
        		bat "msbuild source/AMF.Parser.sln /p:Configuration=Release /p:Platform=\"Any CPU\""
            }
        }
        stage('Test') {
            steps {
                dir("source/AMF.Parser.TestRunner/bin/Release/"){
                    bat 'ConsoleApp2.exe'
                }
            }
        }
        stage('Pack') {
            steps {
                // zip files
                zip dir:'source/AMF.Parser/', zipFile: 'AMF.Parser.zip'
            }
        }        
    }

    post {
        always {
            archiveArtifacts '*.zip'
            notifySlack(currentBuild.currentResult)
        }
        cleanup {
            
            cleanWs()
        }
    }
}