#%RAML 1.0
title: any type
types:
  foo:
    properties:
      anobj: any
      user: string
      age: integer
/root:
  get:
    responses:
      200:
        body:
          application/json:
            type: foo
/bar:
  post:
    body:
      application/json:
        type:
          properties:
            baz: any
            other: string