#%RAML 1.0
title: Maps
version: 1.0
baseUri: http://maps.com/api
mediaType: application/json
types:
    ArrayOfInt: 
        type: array
        items:
            type: integer
        example: [1,2,3,4,5]
    Person:
        type: object
        properties:
            lastname: 
                type: string
                required: true
                maxLength: 255
            firstname: string
    ArrayOfPerson:
        type: Person[]
        example: |
            [
                {
                    "lastname": "smith"
                    "firstname" : "john"
                },
                {
                    "lastname": "jackson"
                    "firstname" : "peter"
                }
            ]
    ArrayOfObject:
        type: array
        items:
            type: object
            properties:
                lastname: 
                    type: string
                    required: true
                    maxLength: 255
                firstname: string
        example: |
            {
                {
                    "lastname": "smith"
                    "firstname" : "john"
                },
                {
                    "lastname": "jackson"
                    "firstname" : "peter"
                }
            }

/persons:
  get:
    responses:
      200:
        body:
          schema: ArrayOfPerson
  post:
    description: adds a movie to the catalogue
    body:
      application/json:
        schema: ArrayOfInt