#%RAML 1.0
title: Dates
version: 1.0
mediaType: application/json
types:
    person:
        type: object
        properties:
            lastname: 
                type: string
                required: true
                maxLength: 255
            firstname: string
            born: date-only
    user:
        properties:
            username:
            lastaccess: datetime
    sample:
        properties:
            prop1: time-only
            prop2: datetime-only
/persons:
  get:
    responses:
      200:
        body:
          schema: person[]
  post:
    body:
      application/json:
        schema: user
  put:
    body:
      application/json:
        schema: sample
/access:
  get:
    responses:
      200:
        body:
          schema: datetime[]