#%RAML 1.0
title: Error reporting
version: 1.0
baseUri: http://errors.com/api
types:
    ArrayOfInt: 
        type: array
        items:
            type: integer
        example: ["1",2,3,4,5]
    Person:
        type: object
        properties:
            lastname: 
                type: string
                required: true
                maxLength: 255
            firstname: string
    ArrayOfPerson:
        type: Person[]
        example: |
            [
                {
                    "firstname" : "john"
                },
                {
                    "lastname": "jackson",
                    "firstname" : "peter"
                }
            ]
    ArrayOfObject:
        type: array
        items:
            type: object
            properties:
                lastname: 
                    type: string
                    required: true
                    maxLength: error
                firstname: string
        example: |
            {
                {
                    "lastname": "smith",
                    "firstname" : "john"
                },
                {
                    "lastname": "jackson",
                    "firstname" : "peter"
                }
            }

/persons:
  get:
    responses:
      body:
        schema: ArrayOfPerson
  post:
    description: adds a movie to the catalogue
    body:
      schema: ArrayOfInt