#%RAML 1.0 Library 
# This file is located at libraries/files.raml 
usage: |
  Use to define some basic file-related constructs.
uses:
  file-type: !include file-type.raml
traits:
  drm:
    headers:
      drm-key:
resourceTypes:
  file:
    get:
      is: [drm]
    put:
      is: [drm]