#%RAML 1.0
title: Api
baseUri: http://mocksvc.mulesoft.com/mocks/00dfd4fb-9343-4d5a-ab6f-75f35cb00456
mediaType: application/xml
types:
    PurchaseOrderType: !include ipo.xsd
    ItemsType: !include ipo.xsd
/orders:
    post:
        description: Create a new purchase order
        body:
            schema: PurchaseOrderType
    /{id}:
        get:
            description: gets an order by id
            responses:
                200:
                    body:
                        schema: PurchaseOrderType
        put:
            description: updates an order
            body:
                schema: PurchaseOrderType
        /ship:
            put:
                description: ship one or more order items
                body:
                    schema: ItemsType
        /notshipped:
            get:
                description: gets the items of an order
                responses:
                    200:
                        body:
                            schema: ItemsType
        /shipped:
            get:
                description: gets the already shipped items of an order
                responses:
                    200:
                        body:
                            schema: ItemsType