#%RAML 1.0
title: Unions
version: 1.0
baseUri: http://maps.com/api
mediaType: application/json
types:
    Person:
        properties:
            lastname: 
            firstname:
    Company:
        properties:
            name:
            address:
    Customer:
        type: Person | Company

/customers:
  get:
    responses:
      200:
        body:
          type: Customer[]
  post:
    body:
      application/json:
        type: Customer