#%RAML 1.0
title: salesOrder api
version: v1
mediaType: application/json
uses:
    types: uses-case-types.raml
    common: uses-case-commonTypes.raml
types:
    lineItem:
        type: object
        properties:
            quantity:
                type: integer
                minimum: 1
                maximum: 99
    salesOrderItemPrototype:
        type: lineItem
        properties:
            product: types.url
    salesOrder:
        type: object
        properties:
            id: common.guid
            created: datetime
            itemSubTotal: common.monetaryValue
            items:
                type: salesOrderItemPrototype[]
    salesOrderLinks:
        type: object
        properties:
            self: types.link
            user: types.link
/salesOrders:
    get:
    /{salesOrderId}: