#%RAML 1.0 Library

types:
    TypeA:
        type: object
        properties:
            a: string[]


    TypeB:
        type: object
        properties:
            b:
                type: string[]

    TypeC:
        type: object
        properties:
            d:
                type: array
                items:
                    type: string

    TypeE:
        type: string[]

    TypeF:
        type: array
        items:
            type: string
