#%RAML 0.8
title: EPiServer.ServiceAPI
version: 1.4.0
baseUri: https://localhost:443/episerverapi/
protocols: [HTTPS]
securitySchemes:
  - oauth_2_0: 
      description: oauth2 secures this API
      type: OAuth 2.0
      describedBy:
        headers:
          Authorization:
            description: |
              Used to send a valid OAuth 2 access token. 
            type: string
        responses:
          401:
            description: |
              Bad or expired token. This can happen if the user or ServiceAPI revoked or expired an access token. To fix, you should re-authenticate the user.
          403:
            description: |
              Bad OAuth request (wrong consumer key, bad nonce, expired timestamp...). Unfortunately, re-authenticating the user won't help here.
      settings:
        authorizationUri: https://localhost:8081/oauth/authorize
        accessTokenUri: https://localhost/episerverapi/token
        authorizationGrants: [ password ]
        scopes:
          - read
          - write
/token:
  displayName: Authorize
  description: Used to obtain access tokens for the EPiServer ServiceAPI
  post:
    description: request an access token for a username, password couplet
    body: 
      application/x-www-form-urlencoded:
        formParameters:
          grant_type:
            description: the type of grant; usually this is "password".
            type: string
            required: true
            pattern: password
          username:
            description: the username requesting access
            type: string
            required: true
          password:
            description: the password value that authenticates the username.
            type: string
            required: true
    responses:
      200:
        description: access is granted and an access token returned
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "title": "Access Token",
                "description": "An Access Token returned by a successful authorization request",
                "type": "object",
                "properties": {
                  "access_token": {
                    "type": "string"
                  },
                  "token_type": {
                    "type": "string",
                    "pattern" : "bearer"
                  },
                  "expires_in": {
                    "type": "integer",
                    "minimum": 1
                  }
                },
                "required": ["access_token", "token_type", "expires_in"]
              }
            example: |
              {
                "access_token": "MLEsudWH9-uopvpQYP9-uO-TXUEg",
                "token_type": "bearer",
                "expires_in": 3599
              }
      400:
        description: access is not granted
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "title": "Access Request Error",
                "description": "When a token is not generated",
                "type": "object",
                "properties": {
                  "error": {
                    "type": "string"
                  }
                },
                "required" : ["error"]
              }
            example: |
              {
                "error": "invalid_grant"
              }
/version:
  displayName: Api Version
  description: Versioning the EPiServer ServiceAPI
  securedBy: [oauth_2_0]
  get:
    description: Obtain the version of the EPiServer ServiceAPI
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "title": "API Version",
                "description": "A Version description for the EPiServer ServiceAPI",
                "type": "object",
                "properties": {
                  "Component": {
                    "type": "string"
                  },
                  "Version": {
                    "type": "string"
                  }
                },
                "required": ["Component", "Version"]
              }
            example: |
              {
                "Component":"EPiServer.ServiceApi",
                "Version":"1.4.0"
              }