#%RAML 0.8
title: Movies
version: 1.0
baseUri: http://movies.com/api
mediaType: application/json
schemas:
    - person: |
          {
            "$schema": "http://json-schema.org/draft-03/schema",
            "type": "object",
            "id": "person",
            "description": "a movie",
            "properties": {
                "id": { "type": "integer"},
                "firstname": { "type": "string"},
                "lastname": { "type": "string" }
            }
          }
    - movie: |
          {
            "$schema": "http://json-schema.org/draft-03/schema",
            "type": "object",
            "id": "movie",
            "description": "a movie",
            "properties": {
                "id": { "type": "integer"},
                "name": { "type": "string"},
                "director": { 
                    "$ref": "person"
                },
                "genre": { "type": "string" },
                "cast":{ "type": "string" },
                "duration":{ "type": "number" },
                "storyline":{ "type": "string" },
                "language":{ "type": "string" }
            }
          }
    - movies: |
            {
              "$schema": "http://json-schema.org/draft-03/schema",
              "type": "array",
              "description": "movies",
              "items": 
                {
                  "$ref": "movie"
                }
            }
/movies:
  get:
    description: gets all movies in the catalogue
    responses:
      200:
        body:
          schema: movies
  post:
    description: adds a movie to the catalogue
    body:
      application/json:
        schema: movie
/persons:
  /{id}:
    get:
      description: get the info of a person
      responses:
        200:
          body:
            application/json:
              schema: person