#%RAML 1.0 Library

uses: 
  common: /exchange_modules/org.mule.templates/banking-common/1.0.1/banking_common.raml

types: 
  
  AccountOwner: 
    type: object
    description: owner of account in bank
    properties:  
      user_id: 
        type: string
        description: identifier of user
      ssn: 
        type: common.SSN
        description: social security number
      display_name: 
        type: string 
        description: display name of account owner 

  AccountBalance:
    type: object
    description: Account balance
    properties:
      id?: 
        type: string | integer
        description: account identifier for Bank
      number: 
        type: string
        description: account number
      balance?: 
        type: common.Money
        description: amount of money held in an account with all reservations
      available_balance?: 
        type: common.Money
        description: available amount of money held in an account
  
  Account:
    type: AccountBalance
    description: Account in Bank
    properties:
      label?: 
        type: string
        description: display name of account
      owners?: 
        type: AccountOwner[]
        description: list of account owners
      overdraft?: 
        type: boolean
        description: A deficit in a bank account caused by drawing more money than the account holds
      overdraft_allowed?: 
        type: common.Money
        description: A deficit in a bank account which is accepted from Bank 
      type?: 
        type: string
        description: type of bank account
      IBAN?: 
        type: string
        description: international bank account number
        pattern: ^[A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}$
      swift_bic?: 
        type: string
        description: international bank identifier code
      bank_id?: 
        type: string
        description: bank identifier
      interest_rate_pa?: 
        type: number
        format: double
        description:  percentage sum that is charged on a yearly or annual basis
      monthly_fee?: 
        type: common.Money
        description: the amount of fee per month
      created_at?: 
        type: datetime
        description: date of created account
      updated_at?: 
        type: datetime
        description: date of last modification