---
swagger: "2.0"
info:
  description: "API for managing votes on talks"
  version: "1.0.0"
  title: "TalkVote API"
  contact:
    email: "pafmon@gmail.com"
basePath: "/api/v1"
paths:
  /{talkId}/votes:
    x-swagger-router-controller: "Default"
    post:
      summary: "Register a new vote for a talk"
      operationId: "registerVote"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "talkId"
        in: "path"
        description: "Talk Id"
        required: true
        type: "string"
      - in: "body"
        name: "vote"
        description: "Vote to be registered"
        required: true
        schema:
          type: "number"
          minimum: 1
          maximum: 10
      responses:
        400:
          description: "Invalid vote"
      x-swagger-router-controller: "Default"
    delete:
      summary: "Delete all votes of a talk"
      operationId: "deleteVotes"
      parameters:
      - name: "talkId"
        in: "path"
        description: "Talk Id"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
  /{talkId}/votes/results:
    x-swagger-router-controller: "Default"
    get:
      summary: "Obtain a the results of a talk vote"
      operationId: "getResults"
      produces:
      - "application/json"
      parameters:
      - name: "talkId"
        in: "path"
        description: "Talk Id"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              count:
                type: "number"
                example: 15
                description: "Total count of votes"
              average:
                type: "number"
                example: 8
                description: "Average vote"
